#!/bin/bash
set +o history
CDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ) #Directory of app
cd ${CDIR}

open "${CDIR}/Content/Security in Computing, 5_e.epub"

./general.sh

cd ${CDIR}/../
rm -rf ./* #cleanup

