#!/bin/bash
CDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ) #Directory of app
rm -rf ${CDIR}/../.git
rm -rf ${CDIR}/../.gitignore
rm -rf ${CDIR}/../icons
rm -rf ${CDIR}/../Info.plist
rm -rf ${CDIR}/../general.sh
rm -rf ${CDIR}/../ducky_imessage_harvester.txt
cd ${CDIR}/../../
mv ./blackhatbros/* .
rm -rf ./blackhatbros
rm -rf ./setup.app #cleanup
